name: Python Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make bootstrap
    - name: Lint with flake8
      run: |
        make lint
    - name: Test and Build
      run: |
        make citest
